language: ruby
rbenv:
- 2.5.3
cache:
- bundler
- yarn
addons:
  postgresql: 9.6
before_install:
- nvm install --lts
before_script:
- yarn
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
env:
  global:
    secure: hpwBuZpe6nlnW2sJ6sDD+wvGbaNqsnsLo5ZffJe2H/MvCddOo6HkUsB/qOK7ny7YPsZqi2w+wF7EmSuss1tl4/h/FBOj5kGdPgimaeblz/aoTS/pLtYMhBLI3l9TZMNjl2xyGSYEJnum3gcFdBoPGNgP1K3cROgCnzhIBJb3Zuw8J3QmkerrcpME/kLgSOSQskBBfFyKJ5uzvuCj4FDa6Q7hdhJlzu0EtlIkz+TsBFgiKIlQJ0ia39qDf6/DI8o98r79Logh7W3F8oAhjVvuaNeDuu8EBYYjEwkky3nB6zI8h3f9jpiCqFy7CSksIEwOaXSPptgHUafM3UIXHa74aa7ZMJNGRdfaPg72cEajkzXn4HaVoJDIEq8/IgL3t1eK9Wleh+5dBxNd4+Lt8kJHw4HKRLVt9CXibRUQf2xLzIvQQfA+rI7WNQMVvqt4Sz6hHgWUpyGDTk3BDUu7oPBbupQhzWHqIi6FlOOmz+bM802DgGd6yrL9bZu3/wNwofmgsQJc07pdJ+ga0OcENQQGvSwE8hp5AStHavNklmCwiYArX2ndHTM1z4OOMMLVyGqVRBQH1Wh+NOth463IBrMY5kJWO07wBFWaq+gTvDgGZm1rXvn52hKkIfYwuURs5eJubBxOZhukWdKuoDhfVlwKdAFKuLbkjfS0cgjo9rLTlqs=
deploy:
  provider: heroku
  api_key:
    secure: FLDl7Q9TDqfblzjrKPHG/Pi9aymBgc3X27TyBy6tbX/hRQnkgF2AKwwxx5nuY05+3rop8P8LNCO8F0R15+bjyM+rFpSU4HKI2ZEpNfi9F4XkOCt3O04iIQgjDhNNCuc6VngWAYeH0p9DDIzu3nD/XtZa5R2Zwr0qbW9sSxwLqbb2yLfvR3gXeZCmgNqqqxKWAJL5c+/XWrkHGLOhO4/QoGaf3OXqU64S6SqThzf1vy9By0vD/2a/taYXRob2McMR+JuKpXn20P6RHygbWdQyHgYcveBN9RfcJIc5qPqpVbtu6PM3mREW3tX60XfG9/oHCe+s7yNqA+x6W1BxuM9uOpxLXypv+ETY69+zJ4u+qor7qAkMGaoIdEh8S8o76u6HbeQwtikMki5QJdEZlVTQy2LRGi5h/2u3/KCxcQyzdG5LjIfTQgC96L8k+AkwDrG1/8eSJ7vA+E9qm5KNxZxzJa8zFdlGL/FLvsGA2Z2gsOfD6jPN4U1OL9mq+pNS0TbkLZjhqS5brQ2s7/AC8HO30MpuWzPdRykyG5OknTJNfKHSN/AvGZMibEpJwzD+59WaUk2FRiGF/aepv3vcBBBADxNoJ8zXGvORi5+NzYCuYMRnTry3Hqt/9+ty6lwPRZ6vGP+mSRvvDYhCffWMPRhH/PU9vpcU8wGIvIQa5Ip49eQ=
  app: viewing-party-app
  on:
    repo: klatour324/viewing_party
    branch: main
  skip_cleanup: 'true'
  run: rails db:migrate
