language: ruby
rbenv:
- 2.5.3
cache:
- bundler
- yarn
addons:
  postgresql: 9.6
before_install:
- nvm install --lts
before_script:
- yarn
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
env:
  global:
    secure: hpwBuZpe6nlnW2sJ6sDD+wvGbaNqsnsLo5ZffJe2H/MvCddOo6HkUsB/qOK7ny7YPsZqi2w+wF7EmSuss1tl4/h/FBOj5kGdPgimaeblz/aoTS/pLtYMhBLI3l9TZMNjl2xyGSYEJnum3gcFdBoPGNgP1K3cROgCnzhIBJb3Zuw8J3QmkerrcpME/kLgSOSQskBBfFyKJ5uzvuCj4FDa6Q7hdhJlzu0EtlIkz+TsBFgiKIlQJ0ia39qDf6/DI8o98r79Logh7W3F8oAhjVvuaNeDuu8EBYYjEwkky3nB6zI8h3f9jpiCqFy7CSksIEwOaXSPptgHUafM3UIXHa74aa7ZMJNGRdfaPg72cEajkzXn4HaVoJDIEq8/IgL3t1eK9Wleh+5dBxNd4+Lt8kJHw4HKRLVt9CXibRUQf2xLzIvQQfA+rI7WNQMVvqt4Sz6hHgWUpyGDTk3BDUu7oPBbupQhzWHqIi6FlOOmz+bM802DgGd6yrL9bZu3/wNwofmgsQJc07pdJ+ga0OcENQQGvSwE8hp5AStHavNklmCwiYArX2ndHTM1z4OOMMLVyGqVRBQH1Wh+NOth463IBrMY5kJWO07wBFWaq+gTvDgGZm1rXvn52hKkIfYwuURs5eJubBxOZhukWdKuoDhfVlwKdAFKuLbkjfS0cgjo9rLTlqs=
deploy:
  provider: heroku
  api_key:
    secure: i/L0mwqTLsNQ9RHbyRIIN7kW6Z1k+/gslx2Vwe7XsTq9djIjCp4bHmfy/vQIvsAuQKjoBJIzXiwbPAuyX9qpSkHDyWfo7pn1hk2vqHEh7rDdUC4DjgoFU1EiCt/LlIapHdW4x7THdhL1Sh/iekzJbynJ0ECLZxrwFBlT0alo9KhHZBmVZ6HjeUc99jgK6KtIFQKE/EQM6eroFYvwMDROP5Q9GYUt6XWcEXiq7wiQgN/Extskip+I9eVL+b+MxJYInO3wNahat9HJyDWhxUnx8mQVXDMu251s/oLrk8FcX5Dtz2Usl8j7MKtUDejLsG+lT5axLhzYxhUQv2Lm1HSwJ71VINXF9LUc51Eq/zLhTgOUaMBXORCM5p1JIh3hndv9bQW0NwON/NkaOw5jcBMnZnySr6WTcnOtmqVidxf69IRCUI+g0RQsMHp2kWSw2M9clfp87GIisBYHwkLQ+8y1jCEch04BwKWbqfEARgA6MKJgtxZ3N11nvia6bMYGXdZaKYPKq7b4RfN0Um09KN605wFam9UgxoRWVnu0zqIvRU30Pn7RQK1yChNyt76iVM2Hdfr0eBGTBph03yAf/eXAwIb4MSzT+G1YiLZyAEKdgY2KYQE/qZ4WL7OCoBs0TwlMm1rYriuSLT227EM2k/eBy4drohgb8fzOCxynBobxwCI=
  app: viewing-party-app
  on:
    repo: klatour324/viewing_party
    branch: main
  skip_cleanup: 'true'
  run: rails db:migrate
