language: ruby
rbenv:
- 2.5.3
cache:
- bundler
- yarn
addons:
  postgresql: 9.6
before_install:
- nvm install --lts
before_script:
- yarn
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
env:
  global:
    secure: hpwBuZpe6nlnW2sJ6sDD+wvGbaNqsnsLo5ZffJe2H/MvCddOo6HkUsB/qOK7ny7YPsZqi2w+wF7EmSuss1tl4/h/FBOj5kGdPgimaeblz/aoTS/pLtYMhBLI3l9TZMNjl2xyGSYEJnum3gcFdBoPGNgP1K3cROgCnzhIBJb3Zuw8J3QmkerrcpME/kLgSOSQskBBfFyKJ5uzvuCj4FDa6Q7hdhJlzu0EtlIkz+TsBFgiKIlQJ0ia39qDf6/DI8o98r79Logh7W3F8oAhjVvuaNeDuu8EBYYjEwkky3nB6zI8h3f9jpiCqFy7CSksIEwOaXSPptgHUafM3UIXHa74aa7ZMJNGRdfaPg72cEajkzXn4HaVoJDIEq8/IgL3t1eK9Wleh+5dBxNd4+Lt8kJHw4HKRLVt9CXibRUQf2xLzIvQQfA+rI7WNQMVvqt4Sz6hHgWUpyGDTk3BDUu7oPBbupQhzWHqIi6FlOOmz+bM802DgGd6yrL9bZu3/wNwofmgsQJc07pdJ+ga0OcENQQGvSwE8hp5AStHavNklmCwiYArX2ndHTM1z4OOMMLVyGqVRBQH1Wh+NOth463IBrMY5kJWO07wBFWaq+gTvDgGZm1rXvn52hKkIfYwuURs5eJubBxOZhukWdKuoDhfVlwKdAFKuLbkjfS0cgjo9rLTlqs=
deploy:
  provider: heroku
  api_key:
    secure: MwWLYd2xJHOdZA1cPD+rhdScYnHygcJMMHz3JhmBSbZtb+1CKOJnKe3gNz+X0ZL9sfLrqvbAqWmDVcv0BdMICGEMYm0ufRP8y3wXbu0qghCQVuSbYIWlor7KC1EetuM25FAmQoZHPAKlvl2XCwSOWJEszS2/cliKzdTVyRS5m2mTtEtwLOb0ralgPb81EgCqsKZ5P3Gwq9oUjOx5tWvY8zH/OHh7Iqsqbf5VPNosH5mu75zdBlH/dlRuspIMKWVVjq9rp3VUfc0Rl365Nz9emeQVUwso076yQOItAA8+2ReSCxfxAVDWpnNmkdfDlZ8+Ue3wVUzxRDJfzHSZ78a2avgFXp/2E31xazRS34jVirl8O7k+yNvKcnl8kaLbVa+GzEURSx1dTLVWQwfUw8TlOd2P8Ukv/ZdCjcJ2gOPR3WTNLpibvgZrrC+D3teJ4Enk3xa7B3xwbnSv2rmuFVGRMZ/wNgYKjze/WGykmyMV6fv5WNIWz1jr1R58pBJOrjv8QrO5UfthsrMEz1i4/eYHYrEZskxJJSO/bJmQt329QVfBj8VOg0rjgByq6E7b9bYyK2AaCfJy7Id/LviHzPecWa9B5G6oISlXFDKLmwbXKvv0Au9dwdPMb454KlUXDFzs68o7LIbOK9UdHXNgqzDtsnWt4wLurNXxCVrmJzyxEmA=
  app: viewing-party-app
  on:
    repo: klatour324/viewing_party
    branch: main
  skip_cleanup: 'true'
  run: rails db:migrate
